### ISSUE TITLE
Add save state

### ISSUE THREAD

**Issue by beudbeud** [celerizer/tamalibretro#3]
It will be nice to have save sate for can quit the core without back to egg state when back in core.

**Comment by celerizer** [comment]
Hi. Savestates should be supported already:

https://github.com/celerizer/tamalibretro/blob/master/main.c#L544
https://github.com/celerizer/tamalibretro/blob/master/main.c#L581

**Comment by celerizer** [comment]
Closed as already supported / related to https://github.com/celerizer/tamalibretro/issues/2
